[project]
name = "disaster-tracker-backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "geopandas>=1.2.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pydantic-settings>=2.15.0",
    "pyproj>=3.8.0",
    "python-dotenv>=1.2.4",
    "rasterio>=1.5.2",
    "requests>=2.34.2",
    "shapely>=2.1.2",
]
